name: "QingBlog 自动构建运行流"

on:
  issues:
    types: [opened, edited, deleted, reopened]

jobs:
  build-blog:
    name: "[核心执行] QingBlog构建"
    runs-on: ubuntu-latest

    permissions:
      contents: write

    defaults:
      run:
        working-directory: .github/scripts

    steps:
      - name: "[代码拉取] 检出代码仓库"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "[环境配置] 配置 Node.js 20.x 环境"
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: "[依赖安装] 安装 Node.js 依赖包"
        run: npm install

      - name: "[构建执行] 启动 Node.js 构建脚本"
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_DATE: ${{ github.event.issue.created_at }}
          ISSUE_AUTHOR: ${{ github.event.issue.user.login }}
          ISSUE_LABELS: ${{ toJson(github.event.issue.labels.*.name) }}
          ISSUE_ID: ${{ github.event.issue.number }}
          ISSUE_ACTION: ${{ github.event.action }}
          BLOG_CONFIG_PATH: "blogData/blogConfig.json"
          PAGES_CONFIG_PATH: "blogData/pagesConfig.json"
        run: node blog-generator.js

      - name: "[变更推送] 提交并推送更改"
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[文章更新] ${{ github.event.action == 'deleted' && '删除文章' || '更新文章' }}: ${{ github.event.issue.title }}"
          file_pattern: '*'
          push_options: '--force-with-lease'
          